# Set up display
SCREEN_WIDTH = 150
SCREEN_HEIGHT = 40
LIMIT_FPS = 20


DESC_CON_WIDTH = 50
DESC_CON_HEIGHT = SCREEN_HEIGHT

INFO_CON_HEIGHT = 5
INFO_CON_WIDTH = SCREEN_WIDTH - DESC_CON_WIDTH - 10


ROOT_CON_WIDTH = SCREEN_WIDTH - DESC_CON_WIDTH
ROOT_CON_HEIGHT = SCREEN_HEIGHT - INFO_CON_HEIGHT
#Model paths
MODEL_URL = "http://6d9d-34-82-193-255.ngrok.io"


GENRE = "Experimental"